### PR TITLE
Fix segfaults with null strings passed to wcscmp

### LINKED ISSUE #288: Segmentation fault in rift.c/get_device_list with VR-Tek WVR2 on Ubuntu
After compiling OpenHMD from master with cmake in debug mode, I ran the simple example with the headset plugged in and got a segmentation fault. Here's my backtrace from `ddd`:

```
in main () at simple.c:58
in ohmd_ctx_probe () at openhmd.c:120
in get_device_list () at rift.c:1081
wcscmp () at wcscmp.S:207
```

The relevant line in `rift.c` is:

`if((wcscmp(cur_dev->manufacturer_string, L"Oculus VR, Inc.") == 0) &&`

I figure something is wrong with `cur_dev->manufacturer_string`. The relevant line from `lsusb` is:

`Bus 001 Device 007: ID 2833:0001  `

It looks like the name is empty. I hope that isn't the source of the segfault.

I should also note that I have installed OpenHMD from apt and the experimental SteamVR drivers from Valve. I also added their udev rules from [here](https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-vr.rules) but didn't mess with OpenHMD udev rules. `xrandr --props` reports the headset as `non-desktop`.

EDIT: When I prepend `if(cur_dev->manufacturer_string &&` to the above, the segfault moves to `vrtek.c` where it checks `cur_dev->manufacturer_string` against `L"STMicroelectronics"`. It's pointless to keep kicking this can down the road, so I would suggest assigning `manufacturer_string` (and others?) to an empty string if null earlier so as to avoid segfaulting `wcscmp`.

EDIT 2: Hmm. What's `hid_enumerate`?

### PR DESCRIPTION
**Pull request by fluffrabbit**
Fixes #288

### CODE REVIEW

**Comment by thaytan** [comment]
LGTM @TheOnlyJoey

File: src/openhmdi.h [hunk 1]
```diff
@@ -143,6 +143,7 @@ void ohmd_set_default_device_properties(ohmd_device_properties* props);
 void ohmd_calc_default_proj_matrices(ohmd_device_properties* props);
 void ohmd_set_universal_distortion_k(ohmd_device_properties* props, float a, float b, float c, float d);
 void ohmd_set_universal_aberration_k(ohmd_device_properties* props, float r, float g, float b);
+int ohmd_wstring_match(const wchar_t *a, const wchar_t *b);
```
Comment (TheOnlyJoey) [inline src/openhmdi.h:146]: This should be implemented in a new utils.h instead of in openhmdi.h (which is just for external facing API).
I was planning in general to move much shared functions to a new utils file, so this would be a good start.

Comment (thaytan) [reply src/openhmdi.h:146]: You might be thinking of include/openhmd.h? openhmdi.h isn't exported API

Comment (fluffrabbit) [reply src/openhmdi.h:146]: What's the consensus on how to proceed?

Comment (thaytan) [reply src/openhmdi.h:146]: I'm good with it how it is, so it's waiting on @TheOnlyJoey

**Comment by fluffrabbit** [comment]
I have no problem with separating it into a new file with helper 
functions. What I wonder in that case is if any other functions could be 
construed as internal helper functions, because there are a number of 
functions doing different things.

File: src/openhmdi.h (hunk 1 above)
Comment (TheOnlyJoey) [reply src/openhmdi.h:146]: Hmm since the openhmdi.h is a template for the internal interface i think it is more clear to implement this into a new utils.h to keep it seperated. (for multiplatform functions, platform specific should still be implemented in the respectful platform-* files.)

**Comment by fluffrabbit** [comment]
@TheOnlyJoey Is this what you had in mind?

File: src/openhmd.c [hunk 2]
```diff
@@ -13,6 +13,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <stdio.h>
+#include <wchar.h>
```
Comment (TheOnlyJoey) [inline src/openhmd.c:16]: I think this include can be (re)moved?

Comment (fluffrabbit) [reply src/openhmd.c]: Yes.

Comment (fluffrabbit) [reply src/openhmd.c]: Windows ninja thing is [breaking](https://ci.appveyor.com/project/Wallbraker/openhmd/builds/33807989/job/6flt4dd9shp22jwu). IDK why. Works fine for me.

Comment (fluffrabbit) [reply src/openhmd.c]: So, `utils.h` is a header with function definitions. MSVC doesn't like the same function in multiple TUs in the same binary, so I'll make it static and see what the CI says.

Comment (fluffrabbit) [reply src/openhmd.c]: OK it's safe to look now. :)

**Comment by fluffrabbit** [comment]
@TheOnlyJoey Okay, a month has passed. Is there anything blocking this merge? Is there anything I should improve, like perhaps squashing commits?

File: src/utils.h [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+ */
+
+/* Utility functions */
+
+#ifndef UTILS_H
+#define UTILS_H
+
+#include <wchar.h>
+
+static int ohmd_wstring_match(const wchar_t *a, const wchar_t *b)
```
Comment (pH5) [inline src/utils.h:15]: Making this `static inline` will silence a bunch of unused function warnings:
> ../src/utils.h:15:12: warning: ‘ohmd_wstring_match’ defined but not used [-Wunused-function]

Comment (fluffrabbit) [reply src/utils.h]: ok done
